### ISSUE TITLE
Relationship to ArrowMonad

### ISSUE THREAD

**Issue by turion** [miguel-negrao/arrow-utils#1]
More of a comment than a ticket.

Note that https://hackage.haskell.org/package/base-4.15.0.0/docs/Control-Arrow.html#t:ArrowMonad exists which is a special case of `SameInputArrow`. It also has the `Applicative` class.

Maybe we can say this in the docs.

**Comment by turion** [comment]
Fixed in #2

**Comment by miguel-negrao** [comment]
Another relationship is that Arrow a b c is a generalization of (a -> b) and ((->) r) has Functor and Applicative [instances](https://hackage.haskell.org/package/base-4.15.0.0/docs/src/GHC-Base.html#%3C%2A%3E):

```
instance Functor ((->) r) where
    fmap = (.)

-- | @since 2.01
instance Applicative ((->) r) where
    pure = const
    (<*>) f g x = f x (g x)
    liftA2 q f g x = q (f x) (g x)
```

**Comment by miguel-negrao** [comment]
Already mentioned in the docs: https://github.com/miguel-negrao/arrow-utils/blob/201d8755fff0fd1eeb77bfd6084ad847c8a39d98/src/Control/Arrow/Utils.hs#L25
