### ISSUE TITLE
Naming of sequenceArrVec

### ISSUE THREAD

**Issue by turion** [miguel-negrao/arrow-utils#4]
Minor issue.

I think `sequenceArrVec` doesn't quite have the right name. `sequenceArrVec` changes the _input_ type of the arrow. It's different from `sequenceArr :: (Traversable t, Arrow a1) => t (a1 b a2) -> a1 b (t a2)`.

Maybe it's helpful to think about what would happen to a Kleisli arrow. If our arrow is secretly of type `a -> m b` for some monad `m`, then `sequenceArrVec` has the type `Vec n (a -> m b) -> Vec n a -> m (Vec n b)`. But I couldn't find any function on Hoogle with that signature. Maybe something like `zipSequenceArrVec`, I'm not sure.

**Comment by miguel-negrao** [comment]
I also thought that it wasn't the correct name but couldn't think of any good one. Lets keep thinking of a better name. Its essentially "gluing" side by side a list of arrows. It's similiar to [***](https://hackage.haskell.org/package/base-4.15.0.0/docs/Control-Arrow.html#v:-42--42--42-) in a way, but instead of combining two arrows combines any number of arrows and the types are the same for input and output. That function doesn't have a name we can use though.

**Comment by miguel-negrao** [comment]
I think sequenceArr is in a way a generalization of `&&&` and sequenceArrVec and  sequenceArrList are a generalization of `***`. The description of `***` is " Split the input between the two argument arrows and combine their output". Perhaps something like "splitCombineVec" for sequenceArrVec and "splitCombineList"  for sequenceArrList ?

**Comment by miguel-negrao** [comment]
@turion Do you have any opinion on the name of these functions ? Should we leave them as they are ? 

I think we can publish an initial version of the library to hackage. I tried enrolling in hackage but never got an email back... have to check how to deal with that.

**Comment by turion** [comment]
> I think sequenceArr is in a way a generalization of `&&&` and sequenceArrVec and sequenceArrList are a generalization of `***`.

Yes, that's a good observation.

> The description of `***` is " Split the input between the two argument arrows and combine their output". Perhaps something like "splitCombineVec" for sequenceArrVec and "splitCombineList" for sequenceArrList ?

Sounds like a good description of what's happening, but I find it quite clunky. I find `zipSequenceArrVec` ok as well, but I think it's your decision :)

**Comment by miguel-negrao** [comment]
Renamed to `zipSequenceArrVec`. Thanks for the input on this.
